### ISSUE TITLE
How do I run coffee on node? 

### ISSUE THREAD

**Issue by jack545** [andrew/ar-drone-keyboard#2]
I have installed coffee but it seems the system is not able to recognize it. Is there an alternative to this code where i could use a js file rather than a coffeee file? kind regards thanks.

**Comment by andrew** [comment]
@jack545 you could convert the coffeescript to javascript using http://js2coffee.org/ if you're having trouble?

**Comment by andrew** [comment]
I'm no longer supporting this library as I don't use it any longer so I'm going to close this issue.
